---
title: "Solutions for day 1"
output: 
  distill::distill_article:
    toc: true
    toc_float: true
    number_sections: true
params:
  showDownload: TRUE
  includeSolution2: TRUE
  includeSolution3: TRUE
  includeSolution4: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r download_script, child= if(params$showDownload) "tasks/day1/01_tasks_download.Rmd"}

```

## 2 Data types and vectors

```{r vectors, child=if (params$includeSolution2) "tasks/day1/01_tasks_02_R_basics_solution.Rmd"}
```


```{r vectors_empty, child=if (!params$includeSolution2) "tasks/day1/01_tasks_02_R_basics_solution_empty.Rmd"}
```

## 3 Tibbles

```{r tibbles, child=if (params$includeSolution3) "./tasks/day1/01_tasks_03_tibbles_short_solution.Rmd"}
```

```{r tibbles_empty, child=if (!params$includeSolution3) "./tasks/day1/01_tasks_03_tibbles_short_solution_empty.Rmd"}
```

## 4 Reading and writing tibbles

```{r readr, child=if (params$includeSolution4) "./tasks/day1/01_tasks_04_readr_solution.Rmd"}
```

```{r readr_empty, child=if (!params$includeSolution4) "./tasks/day1/01_tasks_04_readr_solution_empty.Rmd"}
```

# Reference

Wolfram Research, "Sample Data: Animal Weights" from the Wolfram Data Repository (2016) https://doi.org/10.24097/wolfram.43616.data

