---
title: "Solutions for day 2"
output: 
  distill::distill_article:
    toc: true
    toc_float: true
    number_sections: true
params:
  showDownload: TRUE
  includeSolution1: TRUE
  includeSolution2: TRUE
  includeSolution3: TRUE
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r download_script, echo=FALSE, child= if(params$showDownload) "tasks/day2/02_tasks_download.Rmd"}

```

## 1 ggplot2

```{r ggplot, echo=FALSE, child= if (params$includeSolution1) "tasks/day2/02_tasks_01_ggplot_solution.Rmd"}
```

```{r ggplot_empty,echo=FALSE, child= if (!params$includeSolution1) "tasks/day2/02_tasks_01_ggplot_solution_empty.Rmd"}
```

## 2 dplyr


```{r dplyr, echo=FALSE, child= if (params$includeSolution2) "tasks/day2/02_tasks_02_dplyr_solution.Rmd"}
```

```{r dplyr_empty, echo=FALSE, child= if (!params$includeSolution2) "tasks/day2/02_tasks_02_dplyr_solution_empty.Rmd"}
```

## 3 tidyr

```{r tidyr, echo=FALSE, child= if (params$includeSolution3) "./tasks/day2/02_tasks_04_tidyr_solution.Rmd"}
```

```{r tidyr_empty, echo=FALSE, child= if (!params$includeSolution3) "./tasks/day2/02_tasks_04_tidyr_solution_empty.Rmd"}
```
