---
title: "Tasks for day 3"
output: 
  distill::distill_article:
    toc: true
    toc_float: true
    number_sections: true
params:
  showDownload: TRUE
  includeSolution0: TRUE
  includeSolution1: TRUE
  includeSolution2: FALSE
  includeSolution3: FALSE
  includeSolution4: FALSE
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r download_script, echo=FALSE, child= if(params$showDownload) "tasks/day3/03_tasks_download.Rmd"}

```

## 0 Statistical tests

```{r test, echo=FALSE,child= if (params$includeSolution0) "tasks/day3/03_tasks_00_tests_solution.Rmd"}
```

```{r test_empty,echo=FALSE, child= if (!params$includeSolution0) "tasks/day3/03_tasks_00_tests_solution_empty.Rmd"}
```


## 1 Linear models

```{r lm,echo=FALSE, child= if (params$includeSolution1) "tasks/day3/03_tasks_01_lm_solution.Rmd"}
```

```{r lm_empty, echo=FALSE,child= if (!params$includeSolution1) "tasks/day3/03_tasks_01_lm_solution_empty.Rmd"}
```

## 2 Linear models transformation

```{r lm_trans, echo=FALSE,child=if (params$includeSolution2) "tasks/day3/03_tasks_02_lm_trans_solution.Rmd"}
```

```{r lm_trans_empty,echo=FALSE, child=if (!params$includeSolution2) "tasks/day3/03_tasks_02_lm_trans_solution_empty.Rmd"}
```

## 3 Poisson and binary glm

```{r glm,echo=FALSE, child=if (params$includeSolution3) "./tasks/day3/03_tasks_03_glm_solution.Rmd"}
```

```{r glm_empty,echo=FALSE, child=if (!params$includeSolution3) "./tasks/day3/03_tasks_03_glm_solution_empty.Rmd"}
```

## 4 Proportion glm

```{r glm_prop,echo=FALSE, child=if (params$includeSolution4) "./tasks/day3/03_tasks_04_glm_prop_solution.Rmd"}
```

```{r glm_prop_empty,echo=FALSE, child=if (!params$includeSolution4) "./tasks/day3/03_tasks_04_glm_prop_solution_empty.Rmd"}
```
