project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!*.Rmd"
    - "!additional_docs/"
    - "!R/byod/"
    - "!R/quarto_example.qmd"
  resources:
    - "slides/*.pdf"
    - "slides/*.html"
    - "R/Tasks/"
    - "data/read_challenge/*"
    - "R/byod/general_tips/*"
    - "R/byod/solutions_for_my_datasets/*.R"

website:
  page-navigation: true
  repo-url: "https://github.com/selinaZitrone/intro-r-data-analysis"
  site-url: "https://selinazitrone.github.io/intro-r-data-analysis/"
  repo-actions: [edit, issue]
  repo-branch: master
  page-footer: "Copyright 2025, Selina Baldauf"
  title: ""
  navbar:
    background: "#91BCE6"
    left:
      - text: "<b>Home</b>"
        href: index.qmd
      - text: "Preparations"
        href: preparations.qmd
      - text: "Resources"
        href: online_resources.qmd
      - text: "Packages"
        href: packages.qmd

    right:
      - text: "Sessions"
        menu:
          - text: "<b>Day 1</b>"
          - text: "Introduction RStudio"
            href: sessions/01_intro-rstudio.qmd
          - text: "Introduction R"
            href: sessions/02_intro-r.qmd
          - text: "Functions"
            href: sessions/03_functions.qmd
          - text: "Data frames & tibbles"
            href: sessions/04_data-tibbles.qmd
          - text: "Tidyverse and readr"
            href: sessions/05_readr.qmd
          - text: "---"
          - text: "<b>Day 2</b>"
          - text: "Ggplot2"
            href: sessions/07_ggplot.qmd
          - text: "Dplyr"
            href: sessions/08_dplyr.qmd
          - text: "---"
          - text: "<b>Day 3</b>"
          - text: "Tidyr"
            href: sessions/09_tidyr.qmd
          - text: "Statistical tests"
            href: sessions/10_tests.qmd
          - text: "---"
          - text: "<b>Day 4</b>"
          - text: "Bring your own data"
            href: sessions/slides/bring-your-own-data.qmd
            target: _blank
          - text: "---"
          - text: "<b>Extras</b>"
          - text: "Common R errors"
            href: sessions/06_common-errors.qmd
          - text: "Good practice coding"
            href: sessions/11_good-practice.qmd
          - text: "AI Tools"
            href: sessions/12_AI-tools.qmd
      - text: "Downloads"
        menu:
          - text: "R Script Day 1"
            href: R/Tasks/Day1.R
          - text: "R Script Day 2"
            href: R/Tasks/Day2.R
          - text: "R Script Day 3"
            href: R/Tasks/Day3.R
      - text: "BYOD datasets"
        menu:
          - text: "RNAseq data"
            href: byod/dnaseq.qmd
          - text: "Ice cover data"
            href: byod/ice_cover.qmd
          - text: "Paralympics"
            href: byod/olympics.qmd
          - text: "Wine quality"
            href: byod/wine.qmd
      - text: "BYOD example scripts"
        menu:
          - text: "RNAseq volcano, heatmap, PCA"
            href: R/byod/general_tips/volcano_heatmap_rnaseq.R
          - text: "Read and combine tables"
            href: R/byod/general_tips/read_and_combine_tables.R
          - text: "Correlation plots"
            href: R/byod/general_tips/correlation_plots.R
          - text: "Perform PCA"
            href: R/byod/general_tips/penguins_pca.R
      - icon: github
        menu:
          - text: Source Code
            url: https://github.com/selinaZitrone/intro-r-data-analysis
          - text: Report an Issue
            url: https://github.com/selinaZitrone/intro-r-data-analysis/issues/new

format:
  html:
    embed-resources: true
    theme:
      light: [flatly, theme.scss]
      dark: [darkly]
    toc: true
    number-sections: true
    number-depth: 3
    code-copy: true
    code-overflow: wrap
    code-line-numbers: false
    highlight-style: arrow

editor: source

execute:
  cache: true
  error: true

