project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!*.Rmd"
    - "!additional_docs/"
    - "!R/byod/"
    - "!R/quarto_example.qmd"
  resources:
    - "sessions/slides_pdf/*.pdf"
    - "R/Tasks/"
    - "data/read_challenge/*"
    - "R/byod/general_tips/*"
    - "R/byod/solutions_for_my_datasets/*.R"
    - "timer_solution.js"

website:
  page-navigation: true
  repo-url: "https://github.com/selinaZitrone/intro-r-data-analysis"
  site-url: "https://selinazitrone.github.io/intro-r-data-analysis/"
  repo-actions: [edit, issue]
  repo-branch: master
  page-footer: "Copyright 2026, Selina Baldauf | Contact: [selina.baldauf@fu-berlin.de](mailto:selina.baldauf@fu-berlin.de)"
  title: ""
  navbar:
    background: primary
    left:
      - text: "<b>Home</b>"
        href: index.qmd
      - text: "Sessions"
        menu:
          - text: "<b>Day 1</b>"
          - text: "Introduction to RStudio"
            href: sessions/01_intro-rstudio.qmd
          - text: "Introduction to R"
            href: sessions/02_intro-r.qmd
          - text: "Data frames & tibbles"
            href: sessions/04_data-tibbles.qmd
          - text: "Tidyverse and readr"
            href: sessions/05_readr.qmd
          - text: "---"
          - text: "<b>Day 2</b>"
          - text: "Data visualization with ggplot2"
            href: sessions/07_ggplot.qmd
          - text: "Data transformation with dplyr"
            href: sessions/08_dplyr.qmd
          - text: "---"
          - text: "<b>Day 3</b>"
          - text: "Tidy data with tidyr"
            href: sessions/09_tidyr.qmd
          - text: "Statistical tests"
            href: sessions/10_tests.qmd
          - text: "---"
          - text: "<b>Day 4</b>"
          - text: "Bring Your Own Data"
            href: sessions/byod.qmd
          - text: "---"
          - text: "<b>Extras</b>"
          - text: "Common R errors"
            href: sessions/06_common-errors.qmd
          - text: "Good practice coding"
            href: sessions/11_good-practice.qmd
          - text: "AI Tools"
            href: sessions/12_AI-tools.qmd
      - text: "Preparations"
        href: preparations.qmd
      - text: "Resources"
        href: resources.qmd

    right:
      - icon: github
        menu:
          - text: Source Code
            url: https://github.com/selinaZitrone/intro-r-data-analysis
          - text: Report an Issue
            url: https://github.com/selinaZitrone/intro-r-data-analysis/issues/new

format:
  html:
    theme:
      light: [flatly, theme.scss]
      dark: [darkly, theme.scss]
    toc: true
    number-sections: false
    code-copy: true
    code-overflow: wrap
    code-line-numbers: false
    highlight-style: arrow

editor: source

execute:
  cache: true
  error: true
  freeze: auto

