---
title: "Introduction to R for Data Analysis"
description: |
  Welcome to the workshop. You can find all material and further information this website.
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating websites with Distill at:
# https://rstudio.github.io/distill/website.html

# Learn more about publishing to GitHub Pages at:
# https://rstudio.github.io/distill/publish_website.html#github-pages

```

# Workshop organization and schedule

🕘 9 a.m. - 4 p.m. (🥪 ~ 12 a.m. - 1 p.m.)<br>
📍 We will meet every morning in the `General` meeting romm of you Webex team.

I set up a shared document to collect additional resources, feedback, etc.
You can find the document [here](https://hackmd.io/@selinaZitrone/r12pL71C_/edit), please feel free to edit it as you like.


# Workshop Material

You can find all the workshop material on this website.
On top, you can navigate to the presentation slides and the tasks for each day.
At the end of the workshop day, I will also upload the solutions for each task.

If you want to download presentation slides in pdf format, you can do that with the following links:

- <a href="./slides/01_01_Intro_RStudio_R.pdf" download> 01 - Introduction R and RStudio</a>
- <a href="./slides/01_02_Functions.pdf" download>01 - Functions</a>
- <a href="./slides/01_03_tibbles_short.pdf" download>01 - Data & Tibbles</a>
- <a href="./slides/01_04_readr.pdf" download>01 - Tidyverse and Readr</a>
- <a href="./slides/01_05_common_errors.pdf" download>01 - Common errors</a>
- <a href="./slides/02_01_tidyverse_ggplot.pdf" download>02 - Ggplot2</a>
- <a href="./slides/02_02_dplyr.pdf" download>02 - Dplyr</a>
- <a href="./slides/02_03_tidyr.pdf" download>02 - Tidyr</a>
- <a href="./slides/03_01_linear_models.pdf" download>03 - Linear models</a>
- <a href="./slides/03_02_glm.pdf" download>03 - Generalized linear models</a>




After the workshop is finished, you can download a zipped version of the entire content from [here](download_material_blank.html).





