---
title: "Additional online resources"
description: |
  Below you can find a collection of helpful links to further online resources regarding the workshop topics.
number-sections: false
---

## General

- [List of RStudio cheatsheets](https://www.rstudio.com/resources/cheatsheets/): You can find a list of all the cheat sheets that RStudio provides there. Below, I listed the individual cheat sheets that are interesting for our course.

- [RStudio cheatsheet](https://raw.githubusercontent.com/rstudio/cheatsheets/master/rstudio-ide.pdf): Explains the most important buttons, options, keyboard shortcuts, etc that you have in RStudio.

- [The modern dive book](https://moderndive.com/1-getting-started.html#code) explains how to get started with R and data analysis with the tidyverse.

- The [R for Data Science book](https://r4ds.had.co.nz/index.html) by Hadley Wickham is a very good book to start with. It is specifically about data analysis using the tidyverse packages.

- The [Big book of R](https://www.bigbookofr.com/) is a book that list all books about R that are freely available only. The book is sorted by topics and can be used to find resources to learn a specific topic.

- A [curated collection of R resources](https://github.com/iamericfletcher/awesome-r-learning-resources). Not just books but also websites, tutorials, help channels, ...

- The [Tidyverse style guide](https://style.tidyverse.org/) provides information on how to style your code according to good practice.

- Book [What they forgot to teach you about R](https://rstats.wtf/) by J. Bryan and J. Hesters contains a lot of very nice good practice tips for R code and R projects.

## Tidyverse

- The [tidyverse website](https://tidyverse.org/) has links to all tidyverse packages which all have very good examples and use cases. These websites are an excelent point to get started with a package.

### readr

- [data import cheatsheet](https://raw.githubusercontent.com/rstudio/cheatsheets/master/data-import.pdf)

### ggplot

- [ggplot cheatsheet](https://raw.githubusercontent.com/rstudio/cheatsheets/master/data-visualization-2.1.pdf) offers an overview of all possibilities of ggplot

- [Curated list of ggplot resources](https://github.com/erikgahner/awesome-ggplot2):
Really great list with links to ggplot tutorials (sorted by topic and difficulty), books, additional packages to make your plots look nicer, ...

- In the [R graph gallery](https://www.r-graph-gallery.com/) you can browse through hundreds of different types of plots and find code to reproduce them.

- A great [workshop on ggplot by Cédric Scherer](https://rstudio-conf-2022.github.io/ggplot2-graphic-design/) with everything from basics of ggplot, over using colors, graphic design and plot composition.

 
### dplyr

- [dplyr cheatsheet](https://raw.githubusercontent.com/rstudio/cheatsheets/master/data-transformation.pdf)

### tidyr

- [data import cheatsheet](https://raw.githubusercontent.com/rstudio/cheatsheets/master/data-import.pdf)

## Linear models

- [anova with R](https://stats.libretexts.org/Bookshelves/Applied_Statistics/Book%3A_Learning_Statistics_with_R_-_A_tutorial_for_Psychology_Students_and_other_Beginners_(Navarro)/16%3A_Factorial_ANOVA/16.06%3A_ANOVA_As_a_Linear_Model): explanation why an anova is also a linear model

## Twitter accounts to follow

I personally learn a lot of tricks and find a lot of inspiration and resources by following some R people and accounts on twitter. Often people post helpful tutorials or blogpost that you would not find otherwise. If you are a twitter user, you can try that as well.
Some suggestions that are in no way complete are:

- [Cédric Scherer](https://twitter.com/CedScherer) mainly data visualization and ggplot content
- [Allison Horst](https://twitter.com/allison_horst)
- [RStudio](https://twitter.com/rstudio) official RStudio account
- [Hadley Wickham](https://twitter.com/hadleywickham) data visualisation, tidyverse
- [Jenny Bryan](https://twitter.com/JennyBryan)
- [rOpenSci](https://twitter.com/rOpenSci) develop R tools for open science
- [One R Tip a Day](https://twitter.com/RLangTip) one helpful R tip every day
- [R posts you might have missed](https://twitter.com/icymi_r) repost R blog posts from different topics





