### 4.1 Getting started with tidyr

Before you start, make sure to load the `tidyverse` package.

```{r eval=FALSE}
library(tidyverse)
```

### 4.2 Let's tidy some data sets


**1. `relig_incom`**

Have a look at the `relig_income` data set that is included in tidyverse package.
The data set contains the results of a survey asking people about their religion and income category.

What is not tidy about this data set? Can you fix it?


**2. `billboard`**

Have a look at the `billboard` data set that is included in the tidyverse package.
The data set contains information about the chart rank of songs in the year 2000.

What is not tidy about this data set? Can you fix it?

#### Extras

- Check out the `values_drop_na` argument of `pivot_longer`. What does it do and how can you use it here?
- Check out the `names_prefix` argument of `pivot_longer`. What does it do and how can you use it here?

**3. `fish_encounters`**

Have a look at the `fish_encounters` data set that is included in the tidyverse package.
The data set contains records of fish detected by different automatic monitoring stations. 
Check out `summary(fish_encounters)` - the column `seen` only contains values of 1 to indicate that the fish was seen at the respective station.

What is not tidy about this data set? Can you fix it?

#### Extra

- Have a look at the `values_fill` argument of `pivot_wider`. How could you use it in this case to replace the missing values that are created?
