### 2.1 Getting started

To test the assumptions of linear models, we will use the `performance` package. Make sure you install it once and then load it:

```{r echo=TRUE, eval=FALSE}
install.packages("performance")
library(performance)
```

The `performance` package depends on other packages. It might happen that you encounter an error when trying to load or use the package for the first time. Just read the error message and install the missing packages with `install.packages()` (likely this will be the case for the `qqplotr` package).

**Note:** Finish all the tasks (2.2-2.4) first before you start with the extras.

### 2.2 Linear regression

Let's start with a simple linear regression.

Does the bill depth depend on bill length?

- Make a scatter plot of bill length on the x and bill depth on the y axis.

Now:

- Fit a linear model to test this relationship
- Check for significant effects: What do the results mean?
- Check the model assumptions using diagnostic plots

What do you think? Are the assumptions violated or do the plots look okay?

- Can you add the regression line to the scatter plot?

### 2.3 Analysis of covariance

Does the relationship between bill length and bill depth differ between penguin species?

- Add the species variable as color aesthetic to the scatter plot from 1.2

- Fit the linear model again, including species as second explanatory variable
  - Fit a model **without** interaction between species and bill length

- Test model assumptions the both model

- Check for significant effects models

- Add the regression lines to the plot

#### Extra

- Now fit a model **with** interaction between species and bill length. Test assumptions and significant effects also for this model. Which model would you choose? The one with or without interaction?

Which model would you choose? Add the model results in the scatter plot from before.

### 2.4 Anova

Do the weight of penguins depend on sex and species?

- Before you start exploring this question, remove penguins with missing `sex` variable from the data

- Think of a plot that can represent this question and plot it

- Fit a linear model that represents this question (with interaction between sex and species)

- Test for significant predictors

- Test model assumptions

#### Extra

Improve the looks of the Anova result plot. You can be as creative as you want, e.g. take inspiration from plots you saw in the presentation.

Some ideas:

- Make a boxplot and try to add a combination of `geom_point()` and `position = position_jitterdodge()`

- Make a pointrange plot instead of a boxplot. Here, you need to use the `position = position_dodge(width = 0.5)` argument inside the `stat_summary` function. Otherwise the points for male and female penguins are plotted on top of each other. You can adjust the number `width` for width as you need.

- Same as above but with bars and errorbars instead of pointrange. This is a bit tricky. Make sure to use `position = position_dodge(width = 0.5)` in the `stat_summary` of both the bars and the errorbars. 
