### 3.2 Creating a tibble

Use the vectors `species`, `brainwt_kg`, `bodywt_kg` from the last task and put them in a tibble.

```{r echo=TRUE}
# install.packages("tibble")
library(tibble)

species <- c(
  "MountainBeaver", "Cow", "GreyWolf", "Goat",
  "GuineaPig", "Diplodocus", "AsianElephant", "Donkey",
  "Horse", "PotarMonkey", "Cat", "Giraffe",
  "Gorilla", "Human", "AfricanElephant", "Triceratops",
  "RhesusMonkey", "Kangaroo", "GoldenHamster", "Mouse",
  "Rabbit", "Sheep", "Jaguar", "Chimpanzee",
  "Rat", "Brachiosaurus", "Mole", "Pig"
)

bodywt_kg <- c(
  1.4, 465, 36.3, 27.7, 1., 11700, 2547, 187.1,
  521, 10, 3.3, 529, 207, 62, 6654, 9400,
  6.8, 35, 0.1, 0.02, 2.5, 55.5, 100, 52.2,
  0.3, 87000, 0.1, 192
)

brainwt_g <- c(
  8.1, 423, 119.5, 115, 5.5, 50, 4603, 419, 655, 115, 25.6,
  680, 406, 1320, 5712, 70, 179, 56, 1, 0.4, 12.1, 175,
  157, 440, 1.9, 154.5, 3, 180
)
# Creating the tibble 
animals <- tibble(
  species = species,
  bodywt_kg = bodywt_kg,
  brainwt_kg = brainwt_g / 1000
)
```


### 3.3 Exploring the tibble

In the view window that opens, you have some options to filter the data and sort rows.

```{r echo=TRUE, eval=FALSE}
view(animals)
```

```{r echo=TRUE}
summary(animals)
str(animals)
nrow(animals)
ncol(animals)
names(animals)
```
