### 3.1 Getting started with readr and the tidyverse

Before you start, make sure to install the `tidyverse` packages by calling

```{r eval=FALSE, echo=TRUE}
install.packages("tidyverse")
```

This will install readr along with other tidyverse packages.

Remember to put `library(tidyverse)` (or `library(readr)`) on top of your script to access the readr functions.

### 3.2 Create a tibble and write it

Before we try the `read_*` functions, we will create a tibble in R and save it to disk.

Let's use the tibble with animal brain and body weights from the last task and write it to our project directory.

Before writing the data 

- create a dedicated `data` sub-directory in your project (if you don't have one yet)

Now write the `animals` tibble to that sub-directory. Try writing a file with

- comma separator as csv
- tab separator as txt

Check if the files were written into the correct folder.

### 3.3 Read data into R

Now, try to read the two data sets back into R using the appropriate `read_*()` functions for the separators.

If this was successful, navigate to your `data` directory using the `Files` pane of RStudio.
Try clicking on both the `.txt` and the `.csv` file that you just saved there. What is different? Try the `Import Dataset` button for the `.csv` file.
