### 2.1 Get the data

```{r, echo=TRUE}
prairie <- read.csv("https://raw.githubusercontent.com/selinaZitrone/intro-r-data-analysis/master/data/slides/03_prairiedogs.csv")
```

```{r, echo=TRUE}
# Calculate the number of proportion of survivors
prairie$n.surv <- prairie$n.tot - prairie$n.death
prairie$p.surv <- prairie$n.surv / prairie$n.tot
```

```{r, echo=TRUE}
# Main effects
ggplot(prairie, aes(x = mated, y = p.surv)) + 
  geom_boxplot() +
  ylab("Proportion survivors")

ggplot(prairie, aes(x = hibernation, y = p.surv)) + 
  geom_boxplot() +
  xlab("Hibernation") +
  ylab("Proportion survivors")
#ggsave("prairiedog1.png", width = 6.5, height = 6.5, units = "cm")

ggplot(prairie, aes(x = min.weight, y = p.surv)) + 
  geom_boxplot() +
  ylab("Proportion survivors")

# Two-way interactions
ggplot(prairie, aes(x = mated, y = p.surv, fill = hibernation)) + 
  geom_boxplot() +
  ylab("Proportion survivors")

ggplot(prairie, aes(x = mated, y = p.surv, fill = min.weight)) + 
  geom_boxplot() +
  ylab("Proportion survivors")

ggplot(prairie, aes(x = hibernation, y = p.surv, fill = min.weight)) + 
  geom_boxplot() +
  xlab("Hibernation") +
  ylab("Proportion survivors") +
#ggsave("prairiedog2.png", width = 9, height = 6.5, units = "cm")

# Three way interaction
ggplot(prairie, aes(x = hibernation, y = p.surv,
                   color = min.weight)) +
  geom_point(size = 4) +
  facet_wrap(~mated, labeller = label_both) +
  xlab("Hibernation") + ylab("Proportion survivors") 

#ggsave("prairiedog3.png", width = 10, height = 6.5, units = "cm")

# Fit and analyze models

# 1. Test three-way interaction
mod1 <- glm(cbind(n.surv, n.death) ~ mated*hibernation*min.weight,
            data = prairie, family = "binomial")
drop1(mod1, test = "Chi")
# Not significant

# 2. Test all two way interactions

# Option with two-column response (no. successes, no. failures)
mod2a <- glm(cbind(n.surv, n.death) ~ mated*hibernation +
              mated*min.weight + hibernation*min.weight,
            data = prairie, family = "binomial")
drop1(mod2a, test = "Chi")

# Option with proportion as response and no. total trials ws weights -> same results!
mod2b <- glm(p.surv ~ mated*hibernation +
               mated*min.weight + hibernation*min.weight,
             data = prairie, family = "binomial",
             weights = n.tot)
drop1(mod2b, test = "Chisq")

# 3. Test main effects only
mod3 <- glm(cbind(n.surv, n.death) ~ mated +
              min.weight + hibernation,
            data = prairie, family = "binomial")
drop1(mod3, test = "Chi")
# Only significant main effects of hibernation and min.weight

AIC(mod1, mod2a, mod2b, mod3)
# Model with main effects only is better than
# model with two way interactions according to AIC

# Create plot with data and predictions

# Model with significant predictors only
mod4 <- glm(cbind(n.surv, n.death) ~ 
              min.weight + hibernation,
            data = prairie, family = "binomial")

# New data with all combinations of the significant predictors
new_dat <- expand.grid(hibernation = c("No","Yes"),
                       min.weight = c("No","Yes"))

new_dat$p_surv_pred <- predict(mod4, type = "response", newdata = new_dat)

ggplot(prairie, aes(x = hibernation, y = p.surv,
                   fill = min.weight)) +
  geom_boxplot() +
  geom_point(data = new_dat, aes(y = p_surv_pred,),
             position = position_dodge(width = 0.75),
             shape = 21, size = 5, show.legend = F) +
  ylab("Proportion survivors") 

```

