### 1.1 Explore the visual editor

Open your R Markdown document from the last task. 

Switch to the visual editor by clicking on the RStudio compass button on the top right of 
the document. 

First, scroll through your document and see how it looks different
from the original document view.

Take 5 minutes and explore the visual editor. If you want, you can try to e.g.,

- Insert a link  (`r fontawesome::fa("link")` button)
- Turn some text bold, 
- ...

After you inserted an element, switch back to the normal R Studio editor view 
(click on the compass button again) and see how your original document changed.

### 1.2. Add Citation

#### Add citation of Gorman et al. (2014) via visual editor

First, cite the original paper that published and analysed the penguin data
set. The paper is by Gorman et al. (2014).

Switch to the visual editor and

- Select a location in the text to add the citation
- Click the insert citation button (`@` symbol) on top
- Select `From DOI` and search the DOI `10.1371/journal.pone.0090081`. This should
list the Gorman paper.

Before inserting the citation, have a look at the options that the
`Insert Citation` window offers. 
On the bottom, There is a check box to chose between *in-text* (without brackets) 
or *normal* (in brackets) citation.
You can leave the rest at the default settings. 

Now hit `Insert` and see what changed in the document:

- See how RStudio automatically created a `references.bib` file in your project
(the same location where your `*.Rmd` file is located)
- Open `references.bib` in the editor to see how it looks like
- Look at the YAML header to find the reference file added there automatically

- Knit the document and check that the citation was added correctly in the text and 
that the reference is listed at the end of the document

#### Add citation of the `palmerpenguins` package

Now use a different method to add a second citation of the `palmerpenguins` package. 

Open the `references.bib` file in RStudio (or any other text editor) and add the
following BibTeX entry in a new line:

```bibtex
@Manual{horst2020,
    title = {palmerpenguins: Palmer Archipelago (Antarctica) penguin data},
    author = {Allison Marie Horst and Alison Presmanes Hill and Kristen B Gorman},
    year = {2020},
    note = {R package version 0.1.0},
    doi = {10.5281/zenodo.3960218},
    url = {https://allisonhorst.github.io/palmerpenguins/},
  }
```

Save the file and close it.

Now go to you R Markdown document, switch to the visual editor and select a location
where you want to add the new citation.

- Start typing `@horst2020` in the text. You should see that RStudio starts suggesting
references that match this name. From the list, select the citation of the 
palmerpenguins package.

Knit the document.

Were citation and reference added correctly to the text?

#### Extras

Play with adding both *in-text* and *normal* citations. You can search 
citations via DOI or one of the other methods.
If you have Zotero, you can also try to add a reference from there.