### 2.1 Add other output formats to your document

Go to the YAML section of your R Markdown document and add a new `pdf_document` and
`word_document` (or `odt_document` if you have Open Office instead of MS Word)
into the list of outputs.
For now, just specify, that these outputs should take the `default` values.

Make sure that the indentation is correct.

Know knit your document to these different formats (using the little arrow
next to the `Knit` button) and see how the output looks
like.

### 2.2 Customize your favourite output format

Chose one of the output formats that you'd like to customize a bit more.
Either chose the 
one you like best or the one your are most likely to use for 
your work. If you finish early, you can also try a second output format

#### `pdf_document`

Add some YAML options to this output format e.g. to

- Number the figures
- Add a table of contents
- Change code highlighting
- Give the URLs some color
- Change the font size
- ...

See the [R Markdown cheat sheet](https://raw.githubusercontent.com/rstudio/cheatsheets/master/rmarkdown-2.0.pdf) for YAML options that apply for this document type

#### `word_document`/`odt_document`

Add some YAML options to this output format to

- Number the figures
- Add a table of contents
- Change code highlighting
- ...

See the [R Markdown cheat sheet](https://raw.githubusercontent.com/rstudio/cheatsheets/master/rmarkdown-2.0.pdf) for YAML options that apply for this document type

#### `html_document`

You can

- Insert a tabbed section
- Turn the plot into an interactive one
- Change some of the YAML options that you have not explored so far

See the [R Markdown cheat sheet](https://raw.githubusercontent.com/rstudio/cheatsheets/master/rmarkdown-2.0.pdf) for YAML options that apply for this document type
