We will now add some additional `YAML` metadata and document options
to the document.

In this task, you can test the options that you find most interesting. I will give you
some suggestions to start with and if you still have time, you can explore other
options as well.

Also here, knit your document often, to see the difference that the options make to the document
and make sure that there is no bug.

### 3.1 Add Metadata

- Add today's date to the document
- Add a title and subtitle

### 3.2 Document options

Today, we only worked with `html_document` output. So add some options for this
document type to the YAML header. Be careful to respect the rules of indentation.

Options that might be interesting to try on your document:

- Add a table of contents. Explore the following options (start with those that seem most interesting to you):
  - `toc_depth`: an integer
  - `toc`: `true` or `false`
  - `number_sections`: `true` or `false`
  - `toc_float`: `true` or `false` (HTML only option)
- Try different code highlighting themes using `highlight` option
  - Options are e.g. `"kate"`, `"espresso"` or  `"zenburn"`

#### Extra

- `df_print`: set it to `"kable"` and see how the style of the table that you printed looks like
- Try `code_folding: "hide"` (HTML only option) to hide code and make it available via a button
- Try a different theme, using the `theme` option (HTML only option)
  - Values you can try are `"flatly"`, `"journal"` or `"united"`
  - [Here](https://www.datadreaming.org/post/r-markdown-theme-gallery/) you can find a list of other themes to try
  
- Set the option `code_download` to `true`. See what you can do with the button on the top
right of the document.


Have a look at `?rmarkdown::html_document`. There you find a list of all the options
you can set for an HTML document output. Try some that you find interesting.