### 3.1 Getting started with tibbles

Before you start the task:

- Install the tibble package by calling `install.packages("tibble")` in the console.
- Open your script for the task and put `library(tibble)` on top
- Execute this line and the tibble package is loaded into your R session and ready to use

### 3.2 Creating a tibble

Use the vectors `species`, `brainwt_kg`, `bodywt_kg` from the last task and combine them in a tibble.

Add the following 3 columns to this tibble:

- The ratio of brain weight to body weight
- A column that indicates whether an animal has a large or a small brain
  - Put the string `"large"` into this column if the brain-body weight ratio is higher than 1%
  - Else put `"small"` into the column
- The order of the animals to the data:

```{r eval=FALSE, echo=TRUE}
order <- c(
  "Rodentia", "Artiodactyla", "Carnivora", "Artiodactyla", "Rodentia", NA,
  "Proboscidea", rep("Perissodactyla", 2), NA, "Carnivora", "Artiodactyla",
  rep("Primates", 2), "Proboscidea", "Ornithischia", "Primates", "Diprotodontia",
  "Rodentia", "Rodentia", "Lagomorpha", "Artiodactyla", "Carnivora", "Primates",
  "Rodentia", NA, "Eulipotyphla", "Artiodactyla"
)
```

### 3.3 Exploring the tibble

Explore the tibble you created with the different function that you learned in the presentation.
You can for example try 

- `view()` and explore what you can do in the view window that opens: searching, filtering, sorting columns
- `str()` to view the structure of the data
- `summary()`
- ...

### 3.4 Indexing

Now let's try some indexing on our data.

Try the following selections

- rows 1, 5, and 7 and the columns `species` and `bodywt_kg`
- select rows 1 to 10, all columns
- select the last column of the last row without using the row and column index (so don't use any numbers in this command)
- select only rows that belong to the order of primates, rodentia and carnivora


#### Extra

Create two subsets of the data: one for the small brained animals and one for the large brained animals. To create the subset, you can use the new column with the brain size category that you added before.

Calculate the mean and the standard deviation (`sd()`) of the brain to body ratio for both subsets.
